# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Camilo Costa
email: camilo@bizsoft.com.br
description: > # this means to ignore newlines until "baseurl:"
  Teste com Github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bizsoft.com.br" # the base hostname & protocol for your site
twitter_username: camilogilc
github_username:  camilocosta

# Build settings
markdown: kramdown
